#!/usr/bin/env python3
"""Verify a generated tape-matmul submission under BOTH existing executors.

Executors (this script does not bundle either; they are the referees):

  --python-ref PATH  mask_sparse_parity.py (Python reference executor)
  --dally-eval PATH  dally-eval binary (Rust, cybertronai/dally-eval)
  --n N              matrix size (default 4)

Checks, all of which must pass:
  1. semantic correctness vs numpy (wrapping 8-bit signed matmul)
  2. Python reference: compiles, cost matches the schedule's own fold,
     outputs byte-exact vs numpy on random instances
  3. Rust: `verify` (cost/ops/inputs/outputs JSON) and `cost` agree with
     the Python cost, and `run` scores n/n correct on a fixture whose
     expected bytes come from the Python executor (byte-exact agreement
     between the two executors)
  4. prints the tape-v0 cost breakdown (T_read/T_write as arguments,
     defaults 1/1 per the proposal)
"""
import argparse
import json
import math
import os
import subprocess
import sys
import tempfile

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from generate import generate, lower_to_ir, tape_cost_report, cell_cost  # noqa: E402


def to_signed(b):
    return b.astype(np.int64) - (b >= 128) * 256


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--python-ref", required=True)
    ap.add_argument("--dally-eval", required=True)
    ap.add_argument("--n", type=int, default=4)
    ap.add_argument("--instances", type=int, default=64)
    ap.add_argument("--t-read", type=int, default=1)
    ap.add_argument("--t-write", type=int, default=1)
    ap.add_argument("--seed", type=int, default=20260910)
    args = ap.parse_args()

    n, reps = args.n, args.instances
    schedule = generate(n)
    ir = lower_to_ir(schedule)
    tag = f"matmul_{n}x{n}"

    # 1. numpy ground truth over wrapping 8-bit signed arithmetic
    rng = np.random.default_rng(args.seed)
    A = rng.integers(0, 256, size=(reps, n, n), dtype=np.uint8)
    B = rng.integers(0, 256, size=(reps, n, n), dtype=np.uint8)
    As, Bs = to_signed(A), to_signed(B)
    C = np.empty((reps, n, n), dtype=np.uint8)
    for r in range(reps):
        C[r] = (As[r].astype(np.int64) @ Bs[r]).astype(np.int64) & 0xFF

    # 2. Python reference executor
    spec = importlib_util(args.python_ref)
    simulate_fn, py_cost, n_in = spec._compile_ir(ir, 2_000_000)
    assert n_in == 2 * n * n, n_in
    ok = True
    for r in range(reps):
        inputs = [int(v) for v in list(A[r].ravel()) + list(B[r].ravel())]
        inputs = [v - 256 if v >= 128 else v for v in inputs]  # issue #3: raw, unwrapped
        got = simulate_fn(inputs)
        want = list(C[r].ravel())
        if [g & 0xFF for g in got] != want:
            ok = False
            print(f"MISMATCH instance {r}: python {got} vs numpy {want}")
            break
    print(f"[python] semantic parity vs numpy: {'PASS' if ok else 'FAIL'} ({reps} instances)")
    if not ok:
        sys.exit(1)

    # our own cost fold must match the reference's
    my_cost = sum(
        cell_cost(schedule["operands"][s]) for op in schedule["ops"] for s in op["srcs"]
    ) + sum(cell_cost(e["src_cell"]) for e in schedule["tape"]["write_events"])
    assert my_cost == py_cost, (my_cost, py_cost)
    print(f"[python] static cost = {py_cost} (matches schedule fold)")

    # 3. Rust executor
    with tempfile.TemporaryDirectory() as td:
        ir_path = os.path.join(td, f"{tag}.ir")
        with open(ir_path, "w") as f:
            f.write(ir)
        v = json.loads(
            subprocess.run(
                [args.dally_eval, "verify"], input=ir, capture_output=True, text=True, check=True
            ).stdout
        )
        assert v["cost"] == py_cost, (v, py_cost)
        assert (v["ops"], v["inputs"], v["outputs"]) == (
            schedule["sizes"]["ops"],
            2 * n * n,
            n * n,
        ), v
        cost_cli = int(
            subprocess.run(
                [args.dally_eval, "cost", ir_path], capture_output=True, text=True, check=True
            ).stdout.strip()
        )
        assert cost_cli == py_cost
        print(f"[rust]   verify/cost agree with python: cost = {v['cost']}")

        # fixture: header n, width, ref_cost, then inputs and expected
        # bytes (expected generated BY the python executor)
        py_out = []
        for r in range(reps):
            inputs = [int(v) for v in list(A[r].ravel()) + list(B[r].ravel())]
            inputs = [v - 256 if v >= 128 else v for v in inputs]
            py_out.extend(g & 0xFF for g in simulate_fn(inputs))
        in_bytes = np.concatenate([A.reshape(reps, -1), B.reshape(reps, -1)], axis=1)
        fixture = (
            reps.to_bytes(4, "little")
            + (2 * n * n).to_bytes(4, "little")
            + py_cost.to_bytes(8, "little")
            + in_bytes.astype(np.uint8).tobytes()
            + (reps * n * n).to_bytes(4, "little")  # out_words, per fixture format
            + bytes(py_out)
        )
        fx_path = os.path.join(td, f"{tag}.fixture.bin")
        with open(fx_path, "wb") as f:
            f.write(fixture)
        out = subprocess.run(
            [args.dally_eval, "run", ir_path, fx_path], capture_output=True, text=True, check=True
        ).stdout.strip()
        print(f"[rust]   run: {out}")
        if f"correct {reps}/{reps}" not in out:
            print("BYTE-EXACT AGREEMENT: FAIL")
            sys.exit(1)
    print("BYTE-EXACT AGREEMENT: PASS (python <-> rust <-> numpy)")

    # 4. tape-v0 cost breakdown
    print(json.dumps(tape_cost_report(schedule, args.t_read, args.t_write), indent=1))


def importlib_util(path):
    import importlib.util

    spec = importlib.util.spec_from_file_location("mask_sparse_parity", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


if __name__ == "__main__":
    main()
